/*
 * hc_protocol.h - canonical declaration of the HC device/client protocol.
 *
 * GENERATED by reconcile.py from the three original declarations. Do not edit by hand;
 * edit the generator. `reconcile.py --check` fails the build when this file is stale.
 *
 *   device  belle-fw       b6aaa3d41d2a  sonon/sonon_receive.h
 *   client  moana          7b26a9b27219  framework/SononClient/SononPacket.h
 *   (500C   500c-sn-fw     ca2096a26bb1  src/App/include/USSCustomCommand.h - out of scope, not merged)
 *
 * Drop-in by construction: every original spelling is kept as an alias of the canonical
 * name, so both codebases can include this header without changing a single call site.
 * 원본 이름을 지우는 것은 이 헤더가 양쪽에 들어간 뒤의 별개 작업이다.
 */
#ifndef HC_PROTOCOL_H
#define HC_PROTOCOL_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ---- transport ------------------------------------------------------------------ */
/* 장비가 서버다. 앱이 접속한다. */
#define HC_CTRL_PORT                    1234
#define HC_DATA_PORT                    1235

#define HC_HEADER_SIZE                  14
#define HC_SCAN_DATA_HEADER_SIZE        10

/* ---- header -------------------------------------------------------------------- */
/*
 * 14 bytes on the wire. Byte layout is identical in all three original declarations;
 * verify_layout.c proves it with offsetof/sizeof against the originals themselves.
 *
 * recv_id: the device declares U16, the client declares char[2]. Same bytes, different
 * model - and that divergence has already produced a latent defect. See README "recv_id".
 */
#if defined(_MSC_VER)
#  define HC_PACKED_BEGIN  __pragma(pack(push, 1))
#  define HC_PACKED_END    __pragma(pack(pop))
#  define HC_PACKED
#else
#  define HC_PACKED_BEGIN
#  define HC_PACKED_END
#  define HC_PACKED        __attribute__((packed))
#endif

HC_PACKED_BEGIN
typedef struct hc_header {
    uint8_t  identifier[2];      /* 0  'H','C' */
    uint8_t  version[2];         /* 2  product-line tag, not a protocol version */
    uint16_t recv_id;            /* 4  HC_TARGET_ID_* */
    uint16_t session_id;         /* 6  device reflects the request value */
    uint16_t packet_type;        /* 8  HC_PACKET_TYPE_* */
    uint32_t packet_body_size;   /* 10 */
} HC_PACKED hc_header_t;
HC_PACKED_END

#define HC_HEADER_MAGIC0                'H'
#define HC_HEADER_MAGIC1                'C'

/* version[2] selects the product line; both sides fix it at compile time today. */
#define HC_LINE_300C                    0x0001
#define HC_LINE_300L                    0x0002
#define HC_LINE_300MC                   0x0003
#define HC_LINE_500                     0x0100

/* ---- packet_type - channel/stream class ---------------------------------------- */
#define HC_PACKET_TYPE_DEVICE_COMM                     0x0001   /* belle:HER_PACKET_TYPE_DEVICE_COMM moana:HC_PACKET_TYPE_DEVICE_COMM */
#  define HER_PACKET_TYPE_DEVICE_COMM                  HC_PACKET_TYPE_DEVICE_COMM
#define HC_PACKET_TYPE_DEVICE_RESP                     0x0002   /* belle:HER_PACKET_TYPE_DEVICE_RESP moana:HC_PACKET_TYPE_DEVICE_RESP */
#  define HER_PACKET_TYPE_DEVICE_RESP                  HC_PACKET_TYPE_DEVICE_RESP
#define HC_PACKET_TYPE_FPGA_COMM                       0x0003   /* belle:HER_PACKET_TYPE_FPGA_COMM moana:HC_PACKET_TYPE_FPGA_COMM */
#  define HER_PACKET_TYPE_FPGA_COMM                    HC_PACKET_TYPE_FPGA_COMM
#define HC_PACKET_TYPE_FPGA_RESP                       0x0004   /* belle:HER_PACKET_TYPE_FPGA_RESP moana:HC_PACKET_TYPE_FPGA_RESP */
#  define HER_PACKET_TYPE_FPGA_RESP                    HC_PACKET_TYPE_FPGA_RESP
#define HC_PACKET_TYPE_AGING_TEST_COMM                 0x0005   /* belle:HER_PACKET_TYPE_AGING_TEST_COMM */
#  define HER_PACKET_TYPE_AGING_TEST_COMM              HC_PACKET_TYPE_AGING_TEST_COMM
#define HC_PACKET_TYPE_AGING_TEST_RESP                 0x0006   /* belle:HER_PACKET_TYPE_AGING_TEST_RESP */
#  define HER_PACKET_TYPE_AGING_TEST_RESP              HC_PACKET_TYPE_AGING_TEST_RESP
#define HC_PACKET_TYPE_B_ONLY_SCAN_DATA                0x0100   /* belle:HER_PACKET_TYPE_B_ONLY_SCAN_DATA moana:HC_PACKET_TYPE_SCAN_DATA moana:HC_PACKET_TYPE_B_MODE */
#  define HER_PACKET_TYPE_B_ONLY_SCAN_DATA             HC_PACKET_TYPE_B_ONLY_SCAN_DATA
#  define HC_PACKET_TYPE_SCAN_DATA                     HC_PACKET_TYPE_B_ONLY_SCAN_DATA
#  define HC_PACKET_TYPE_B_MODE                        HC_PACKET_TYPE_B_ONLY_SCAN_DATA
#define HC_PACKET_TYPE_B_C_SCANLINE_DATA               0x0101   /* belle:HER_PACKET_TYPE_B_C_SCANLINE_DATA */
#  define HER_PACKET_TYPE_B_C_SCANLINE_DATA            HC_PACKET_TYPE_B_C_SCANLINE_DATA
#define HC_PACKET_TYPE_B_C_FRAME_DATA                  0x0102   /* belle:HER_PACKET_TYPE_B_C_FRAME_DATA moana:HC_PACKET_TYPE_CF_MODE */
#  define HER_PACKET_TYPE_B_C_FRAME_DATA               HC_PACKET_TYPE_B_C_FRAME_DATA
#  define HC_PACKET_TYPE_CF_MODE                       HC_PACKET_TYPE_B_C_FRAME_DATA
#define HC_PACKET_TYPE_PW_FRAME_DATA                   0x0104   /* belle:HER_PACKET_TYPE_PW_FRAME_DATA belle:HER_PACKET_TYPE_PW_AUDIO_FRAME_DATA moana:HC_PACKET_TYPE_PW_MODE */
#  define HER_PACKET_TYPE_PW_FRAME_DATA                HC_PACKET_TYPE_PW_FRAME_DATA
#  define HER_PACKET_TYPE_PW_AUDIO_FRAME_DATA          HC_PACKET_TYPE_PW_FRAME_DATA
#  define HC_PACKET_TYPE_PW_MODE                       HC_PACKET_TYPE_PW_FRAME_DATA
#define HC_PACKET_TYPE_M_FRAME_DATA                    0x0106   /* belle:HER_PACKET_TYPE_M_FRAME_DATA moana:HC_PACKET_TYPE_M_MODE */
#  define HER_PACKET_TYPE_M_FRAME_DATA                 HC_PACKET_TYPE_M_FRAME_DATA
#  define HC_PACKET_TYPE_M_MODE                        HC_PACKET_TYPE_M_FRAME_DATA

/* ---- DEVICE opcodes (packet_type DEVICE_COMM / DEVICE_RESP) -------------------- */
#define HC_DEVICE_SCAN_READY                           0x0001   /* belle:DEVICE_SCAN_READY moana:DEVICE_SCAN_READY */
#  define DEVICE_SCAN_READY                            HC_DEVICE_SCAN_READY
#define HC_DEVICE_SCAN                                 0x0002   /* belle:DEVICE_SCAN moana:DEVICE_SCAN */
#  define DEVICE_SCAN                                  HC_DEVICE_SCAN
#define HC_DEVICE_KEEP_ALIVE                           0x0003   /* belle:DEVICE_KEEP_ALIVE moana:DEVICE_KEEP_ALIVE */
#  define DEVICE_KEEP_ALIVE                            HC_DEVICE_KEEP_ALIVE
#define HC_DEVICE_POWER_OFF                            0x0004   /* belle:DEVICE_POWER_OFF moana:DEVICE_POWEROFF */
#  define DEVICE_POWER_OFF                             HC_DEVICE_POWER_OFF
#  define DEVICE_POWEROFF                              HC_DEVICE_POWER_OFF
#define HC_DEVICE_APP_SHUTDOWN                         0x0005   /* belle:DEVICE_APP_SHUTDOWN moana:DEVICE_SHUTDOWN */
#  define DEVICE_APP_SHUTDOWN                          HC_DEVICE_APP_SHUTDOWN
#  define DEVICE_SHUTDOWN                              HC_DEVICE_APP_SHUTDOWN
#define HC_DEVICE_FW_UPGRADE                           0x0006   /* belle:DEVICE_FW_UPGRADE moana:DEVICE_FW_UPGRADE */
#  define DEVICE_FW_UPGRADE                            HC_DEVICE_FW_UPGRADE
#define HC_DEVICE_KEY_EVENT                            0x0008   /* belle:DEVICE_KEY_EVENT moana:DEVICE_KEY_EVENT */
#  define DEVICE_KEY_EVENT                             HC_DEVICE_KEY_EVENT
#define HC_DEVICE_READ_SETUP_INFO                      0x000D   /* belle:DEVICE_READ_SETUP_INFO */
#  define DEVICE_READ_SETUP_INFO                       HC_DEVICE_READ_SETUP_INFO
#define HC_DEVICE_WRITE_SETUP_INFO                     0x000E   /* belle:DEVICE_WRITE_SETUP_INFO */
#  define DEVICE_WRITE_SETUP_INFO                      HC_DEVICE_WRITE_SETUP_INFO
#define HC_DEVICE_FW_UPGRADE_SN_START                  0x00F7   /* moana:DEVICE_FW_UPGRADE_SN_START */
#  define DEVICE_FW_UPGRADE_SN_START                   HC_DEVICE_FW_UPGRADE_SN_START
#define HC_DEVICE_FW_UPGRADE_SN_WRITE                  0x00F8   /* moana:DEVICE_FW_UPGRADE_SN_WRITE */
#  define DEVICE_FW_UPGRADE_SN_WRITE                   HC_DEVICE_FW_UPGRADE_SN_WRITE
#define HC_DEVICE_FW_UPGRADE_SN_VERIFY                 0x00F9   /* moana:DEVICE_FW_UPGRADE_SN_VERIFY */
#  define DEVICE_FW_UPGRADE_SN_VERIFY                  HC_DEVICE_FW_UPGRADE_SN_VERIFY
#define HC_DEVICE_FW_UPGRADE_SN_REBOOT                 0x00FA   /* moana:DEVICE_FW_UPGRADE_SN_REBOOT */
#  define DEVICE_FW_UPGRADE_SN_REBOOT                  HC_DEVICE_FW_UPGRADE_SN_REBOOT
#define HC_DEVICE_EMERGENCY                            0x00FF   /* belle:DEVICE_EMERGENCY moana:DEVICE_EMR_EVENT */
#  define DEVICE_EMERGENCY                             HC_DEVICE_EMERGENCY
#  define DEVICE_EMR_EVENT                             HC_DEVICE_EMERGENCY
#define HC_DEVICE_READ_DEVICE_NAME                     0x0100   /* belle:DEVICE_READ_DEVICE_NAME */
#  define DEVICE_READ_DEVICE_NAME                      HC_DEVICE_READ_DEVICE_NAME
#define HC_DEVICE_WRITE_DEVICE_NAME                    0x0101   /* belle:DEVICE_WRITE_DEVICE_NAME */
#  define DEVICE_WRITE_DEVICE_NAME                     HC_DEVICE_WRITE_DEVICE_NAME
#define HC_DEVICE_READ_WIFI_SETUP                      0x0102   /* belle:DEVICE_READ_WIFI_SETUP */
#  define DEVICE_READ_WIFI_SETUP                       HC_DEVICE_READ_WIFI_SETUP
#define HC_DEVICE_WRITE_WIFI_SETUP                     0x0103   /* belle:DEVICE_WRITE_WIFI_SETUP moana:DEVICE_WIFI_SETUP */
#  define DEVICE_WRITE_WIFI_SETUP                      HC_DEVICE_WRITE_WIFI_SETUP
#  define DEVICE_WIFI_SETUP                            HC_DEVICE_WRITE_WIFI_SETUP
#define HC_DEVICE_READ_ENCODE_IMAGE                    0x0104   /* belle:DEVICE_READ_ENCODE_IMAGE */
#  define DEVICE_READ_ENCODE_IMAGE                     HC_DEVICE_READ_ENCODE_IMAGE
#define HC_DEVICE_WRITE_ENCODE_IMAGE                   0x0105   /* belle:DEVICE_WRITE_ENCODE_IMAGE */
#  define DEVICE_WRITE_ENCODE_IMAGE                    HC_DEVICE_WRITE_ENCODE_IMAGE
#define HC_DEVICE_READ_BATTERY                         0x0106   /* belle:DEVICE_READ_BATTERY */
#  define DEVICE_READ_BATTERY                          HC_DEVICE_READ_BATTERY
#define HC_DEVICE_READ_TEMPERATURE                     0x0107   /* belle:DEVICE_READ_TEMPERATURE */
#  define DEVICE_READ_TEMPERATURE                      HC_DEVICE_READ_TEMPERATURE
#define HC_DEVICE_READ_WIFI_MAC                        0x0108   /* belle:DEVICE_READ_WIFI_MAC */
#  define DEVICE_READ_WIFI_MAC                         HC_DEVICE_READ_WIFI_MAC
#define HC_DEVICE_READ_FW_VERSION                      0x0109   /* belle:DEVICE_READ_FW_VERSION moana:DEVICE_FW_VERSION */
#  define DEVICE_READ_FW_VERSION                       HC_DEVICE_READ_FW_VERSION
#  define DEVICE_FW_VERSION                            HC_DEVICE_READ_FW_VERSION
#define HC_DEVICE_READ_DEVICE_INFO                     0x010A   /* belle:DEVICE_READ_DEVICE_INFO moana:DEVICE_DEVICE_INFO */
#  define DEVICE_READ_DEVICE_INFO                      HC_DEVICE_READ_DEVICE_INFO
#  define DEVICE_DEVICE_INFO                           HC_DEVICE_READ_DEVICE_INFO
#define HC_DEVICE_WRITE_DEVICE_INFO                    0x010B   /* belle:DEVICE_WRITE_DEVICE_INFO */
#  define DEVICE_WRITE_DEVICE_INFO                     HC_DEVICE_WRITE_DEVICE_INFO
#define HC_DEVICE_READ_FRAMERATE                       0x010C   /* belle:DEVICE_READ_FRAMERATE */
#  define DEVICE_READ_FRAMERATE                        HC_DEVICE_READ_FRAMERATE
#define HC_DEVICE_WRITE_FRAMERATE                      0x010D   /* belle:DEVICE_WRITE_FRAMERATE moana:DEVICE_FRAMERATE */
#  define DEVICE_WRITE_FRAMERATE                       HC_DEVICE_WRITE_FRAMERATE
#  define DEVICE_FRAMERATE                             HC_DEVICE_WRITE_FRAMERATE
#define HC_DEVICE_READ_NETWORK_SETUP                   0x010E   /* belle:DEVICE_READ_NETWORK_SETUP */
#  define DEVICE_READ_NETWORK_SETUP                    HC_DEVICE_READ_NETWORK_SETUP
#define HC_DEVICE_WRITE_NETWORK_SETUP                  0x010F   /* belle:DEVICE_WRITE_NETWORK_SETUP */
#  define DEVICE_WRITE_NETWORK_SETUP                   HC_DEVICE_WRITE_NETWORK_SETUP
#define HC_DEVICE_READ_DOPPLER_FF_ENABLE               0x0110   /* belle:DEVICE_READ_DOPPLER_FF_ENABLE */
#  define DEVICE_READ_DOPPLER_FF_ENABLE                HC_DEVICE_READ_DOPPLER_FF_ENABLE
#define HC_DEVICE_WRITE_DOPPLER_FF_ENABLE              0x0111   /* belle:DEVICE_WRITE_DOPPLER_FF_ENABLE */
#  define DEVICE_WRITE_DOPPLER_FF_ENABLE               HC_DEVICE_WRITE_DOPPLER_FF_ENABLE
#define HC_DEVICE_EMERGENCY_SELF_TEST                  0x1001   /* belle:DEVICE_EMERGENCY_SELF_TEST */
#  define DEVICE_EMERGENCY_SELF_TEST                   HC_DEVICE_EMERGENCY_SELF_TEST
#define HC_DEVICE_DBG_DEVICE_INFO                      0x1002   /* belle:DEVICE_DBG_DEVICE_INFO */
#  define DEVICE_DBG_DEVICE_INFO                       HC_DEVICE_DBG_DEVICE_INFO
#define HC_DEVICE_SPEC_INFO                            0x2001   /* belle:DEVICE_SPEC_INFO moana:DEVICE_SPEC_INFO */
#  define DEVICE_SPEC_INFO                             HC_DEVICE_SPEC_INFO
#define HC_DEVICE_TIME_SYNC                            0x2002   /* belle:DEVICE_TIME_SYNC moana:DEVICE_TIME_SYNC */
#  define DEVICE_TIME_SYNC                             HC_DEVICE_TIME_SYNC
#define HC_DEVICE_FW_UPGRADE_PROGRESS                  0x2003   /* belle:DEVICE_FW_UPGRADE_PROGRESS moana:DEVICE_FW_UPGRADE_PROGRESS */
#  define DEVICE_FW_UPGRADE_PROGRESS                   HC_DEVICE_FW_UPGRADE_PROGRESS
#define HC_DEVICE_FW_UPGRADE_STATUS                    0x2004   /* belle:DEVICE_FW_UPGRADE_STATUS moana:DEVICE_FW_UPGRADE_STATUS */
#  define DEVICE_FW_UPGRADE_STATUS                     HC_DEVICE_FW_UPGRADE_STATUS

/* ---- FPGA opcodes (packet_type FPGA_COMM / FPGA_RESP) -------------------------- */
#define HC_FPGA_RESET                                  0x0001   /* belle:FPGA_RESET moana:FPGA_RESET */
#  define FPGA_RESET                                   HC_FPGA_RESET
#define HC_FPGA_READ_REG                               0x0002   /* belle:FPGA_READ_REG */
#  define FPGA_READ_REG                                HC_FPGA_READ_REG
#define HC_FPGA_WRITE_REG                              0x0003   /* belle:FPGA_WRITE_REG */
#  define FPGA_WRITE_REG                               HC_FPGA_WRITE_REG
#define HC_FPGA_SHOW_REG                               0x0004   /* belle:FPGA_SHOW_REG */
#  define FPGA_SHOW_REG                                HC_FPGA_SHOW_REG
#define HC_FPGA_PRESET_REG                             0x0005   /* belle:FPGA_PRESET_REG */
#  define FPGA_PRESET_REG                              HC_FPGA_PRESET_REG
#define HC_FPGA_MEM_DUMP                               0x0006   /* belle:FPGA_MEM_DUMP */
#  define FPGA_MEM_DUMP                                HC_FPGA_MEM_DUMP
#define HC_FPGA_LOAD_REG                               0x0007   /* belle:FPGA_LOAD_REG */
#  define FPGA_LOAD_REG                                HC_FPGA_LOAD_REG
#define HC_FPGA_SAVE_REG                               0x0008   /* belle:FPGA_SAVE_REG */
#  define FPGA_SAVE_REG                                HC_FPGA_SAVE_REG
#define HC_FPGA_READ_MAX2082_REG                       0x0009   /* belle:FPGA_READ_MAX2082_REG */
#  define FPGA_READ_MAX2082_REG                        HC_FPGA_READ_MAX2082_REG
#define HC_FPGA_WRITE_MAX2082_REG                      0x000A   /* belle:FPGA_WRITE_MAX2082_REG */
#  define FPGA_WRITE_MAX2082_REG                       HC_FPGA_WRITE_MAX2082_REG
#define HC_FPGA_LOAD_MAX2082_REG_LIST                  0x000B   /* belle:FPGA_LOAD_MAX2082_REG_LIST */
#  define FPGA_LOAD_MAX2082_REG_LIST                   HC_FPGA_LOAD_MAX2082_REG_LIST
#define HC_FPGA_SAVE_MAX2082_REG_LIST                  0x000C   /* belle:FPGA_SAVE_MAX2082_REG_LIST */
#  define FPGA_SAVE_MAX2082_REG_LIST                   HC_FPGA_SAVE_MAX2082_REG_LIST
#define HC_FPGA_LOAD_MAX2082_REG_FILE                  0x000D   /* belle:FPGA_LOAD_MAX2082_REG_FILE */
#  define FPGA_LOAD_MAX2082_REG_FILE                   HC_FPGA_LOAD_MAX2082_REG_FILE
#define HC_FPGA_SAVE_MAX2082_REG_FILE                  0x000E   /* belle:FPGA_SAVE_MAX2082_REG_FILE */
#  define FPGA_SAVE_MAX2082_REG_FILE                   HC_FPGA_SAVE_MAX2082_REG_FILE
#define HC_FPGA_WRITE_B_MODE_PARAM                     0x0010   /* belle:FPGA_WRITE_B_MODE_PARAM moana:FPGA_B_PARAM */
#  define FPGA_WRITE_B_MODE_PARAM                      HC_FPGA_WRITE_B_MODE_PARAM
#  define FPGA_B_PARAM                                 HC_FPGA_WRITE_B_MODE_PARAM
#define HC_FPGA_WRITE_CF_MODE_PARAM                    0x0011   /* belle:FPGA_WRITE_CF_MODE_PARAM moana:FPGA_CF_PARAM */
#  define FPGA_WRITE_CF_MODE_PARAM                     HC_FPGA_WRITE_CF_MODE_PARAM
#  define FPGA_CF_PARAM                                HC_FPGA_WRITE_CF_MODE_PARAM
#define HC_FPGA_WRITE_PW_MODE_PARAM                    0x0012   /* belle:FPGA_WRITE_PW_MODE_PARAM moana:FPGA_PW_PARAM */
#  define FPGA_WRITE_PW_MODE_PARAM                     HC_FPGA_WRITE_PW_MODE_PARAM
#  define FPGA_PW_PARAM                                HC_FPGA_WRITE_PW_MODE_PARAM
#define HC_FPGA_WRITE_M_MODE_PARAM                     0x0013   /* belle:FPGA_WRITE_M_MODE_PARAM moana:FPGA_M_PARAM */
#  define FPGA_WRITE_M_MODE_PARAM                      HC_FPGA_WRITE_M_MODE_PARAM
#  define FPGA_M_PARAM                                 HC_FPGA_WRITE_M_MODE_PARAM
#define HC_FPGA_READ_DEPTH                             0x0100   /* belle:FPGA_READ_DEPTH */
#  define FPGA_READ_DEPTH                              HC_FPGA_READ_DEPTH
#define HC_FPGA_WRITE_DEPTH                            0x0101   /* belle:FPGA_WRITE_DEPTH moana:FPGA_DEPTH */
#  define FPGA_WRITE_DEPTH                             HC_FPGA_WRITE_DEPTH
#  define FPGA_DEPTH                                   HC_FPGA_WRITE_DEPTH
#define HC_FPGA_READ_FOCAL_LENGTH                      0x0102   /* belle:FPGA_READ_FOCAL_LENGTH */
#  define FPGA_READ_FOCAL_LENGTH                       HC_FPGA_READ_FOCAL_LENGTH
#define HC_FPGA_WRITE_FOCAL_LENGTH                     0x0103   /* belle:FPGA_WRITE_FOCAL_LENGTH moana:FPGA_FOCAL */
#  define FPGA_WRITE_FOCAL_LENGTH                      HC_FPGA_WRITE_FOCAL_LENGTH
#  define FPGA_FOCAL                                   HC_FPGA_WRITE_FOCAL_LENGTH
#define HC_FPGA_READ_TGC_CTRL                          0x0104   /* belle:FPGA_READ_TGC_CTRL */
#  define FPGA_READ_TGC_CTRL                           HC_FPGA_READ_TGC_CTRL
#define HC_FPGA_WRITE_TGC_CTRL                         0x0105   /* belle:FPGA_WRITE_TGC_CTRL */
#  define FPGA_WRITE_TGC_CTRL                          HC_FPGA_WRITE_TGC_CTRL
#define HC_FPGA_READ_APP_SETTING                       0x0106   /* belle:FPGA_READ_APP_SETTING */
#  define FPGA_READ_APP_SETTING                        HC_FPGA_READ_APP_SETTING
#define HC_FPGA_WRITE_APP_SETTING                      0x0107   /* belle:FPGA_WRITE_APP_SETTING moana:FPGA_PRESET */
#  define FPGA_WRITE_APP_SETTING                       HC_FPGA_WRITE_APP_SETTING
#  define FPGA_PRESET                                  HC_FPGA_WRITE_APP_SETTING
#define HC_FPGA_READ_DR_CTRL                           0x0108   /* belle:FPGA_READ_DR_CTRL */
#  define FPGA_READ_DR_CTRL                            HC_FPGA_READ_DR_CTRL
#define HC_FPGA_WRITE_DR_CTRL                          0x0109   /* belle:FPGA_WRITE_DR_CTRL moana:FPGA_DR */
#  define FPGA_WRITE_DR_CTRL                           HC_FPGA_WRITE_DR_CTRL
#  define FPGA_DR                                      HC_FPGA_WRITE_DR_CTRL
#define HC_FPGA_DBG_ADC_DUMP                           0x010A   /* belle:FPGA_DBG_ADC_DUMP moana:FPGA_FULL_ADC_DUMP */
#  define FPGA_DBG_ADC_DUMP                            HC_FPGA_DBG_ADC_DUMP
#  define FPGA_FULL_ADC_DUMP                           HC_FPGA_DBG_ADC_DUMP
#define HC_FPGA_READ_FRAME_MODE                        0x010B   /* belle:FPGA_READ_FRAME_MODE */
#  define FPGA_READ_FRAME_MODE                         HC_FPGA_READ_FRAME_MODE
#define HC_FPGA_WRITE_FRAME_MODE                       0x010C   /* belle:FPGA_WRITE_FRAME_MODE */
#  define FPGA_WRITE_FRAME_MODE                        HC_FPGA_WRITE_FRAME_MODE
#define HC_FPGA_READ_PROBE_FLIP                        0x010E   /* belle:FPGA_READ_PROBE_FLIP */
#  define FPGA_READ_PROBE_FLIP                         HC_FPGA_READ_PROBE_FLIP
#define HC_FPGA_WRITE_PROBE_FLIP                       0x010F   /* belle:FPGA_WRITE_PROBE_FLIP moana:FPGA_PROBE_FLIP */
#  define FPGA_WRITE_PROBE_FLIP                        HC_FPGA_WRITE_PROBE_FLIP
#  define FPGA_PROBE_FLIP                              HC_FPGA_WRITE_PROBE_FLIP
#define HC_FPGA_READ_PROBE_TYPE                        0x0110   /* belle:FPGA_READ_PROBE_TYPE moana:FPGA_PROBE_TYPE */
#  define FPGA_READ_PROBE_TYPE                         HC_FPGA_READ_PROBE_TYPE
#  define FPGA_PROBE_TYPE                              HC_FPGA_READ_PROBE_TYPE
#define HC_FPGA_WRITE_PROBE_TYPE                       0x0111   /* belle:FPGA_WRITE_PROBE_TYPE */
#  define FPGA_WRITE_PROBE_TYPE                        HC_FPGA_WRITE_PROBE_TYPE
#define HC_FPGA_READ_FILTER_CTRL                       0x0112   /* belle:FPGA_READ_FILTER_CTRL */
#  define FPGA_READ_FILTER_CTRL                        HC_FPGA_READ_FILTER_CTRL
#define HC_FPGA_WRITE_FILTER_CTRL                      0x0113   /* belle:FPGA_WRITE_FILTER_CTRL */
#  define FPGA_WRITE_FILTER_CTRL                       HC_FPGA_WRITE_FILTER_CTRL
#define HC_FPGA_READ_DTGC_CTRL                         0x0117   /* belle:FPGA_READ_DTGC_CTRL */
#  define FPGA_READ_DTGC_CTRL                          HC_FPGA_READ_DTGC_CTRL
#define HC_FPGA_WRITE_DTGC_CTRL                        0x0118   /* belle:FPGA_WRITE_DTGC_CTRL moana:FPGA_TGC */
#  define FPGA_WRITE_DTGC_CTRL                         HC_FPGA_WRITE_DTGC_CTRL
#  define FPGA_TGC                                     HC_FPGA_WRITE_DTGC_CTRL
#define HC_FPGA_READ_BW_HOLE_FILTER_CTRL               0x0119   /* belle:FPGA_READ_BW_HOLE_FILTER_CTRL */
#  define FPGA_READ_BW_HOLE_FILTER_CTRL                HC_FPGA_READ_BW_HOLE_FILTER_CTRL
#define HC_FPGA_WRITE_BW_HOLE_FILTER_CTRL              0x011A   /* belle:FPGA_WRITE_BW_HOLE_FILTER_CTRL */
#  define FPGA_WRITE_BW_HOLE_FILTER_CTRL               HC_FPGA_WRITE_BW_HOLE_FILTER_CTRL
#define HC_FPGA_READ_B_OFFSET_GAIN_CTRL                0x011B   /* belle:FPGA_READ_B_OFFSET_GAIN_CTRL */
#  define FPGA_READ_B_OFFSET_GAIN_CTRL                 HC_FPGA_READ_B_OFFSET_GAIN_CTRL
#define HC_FPGA_WRITE_B_OFFSET_GAIN_CTRL               0x011C   /* belle:FPGA_WRITE_B_OFFSET_GAIN_CTRL moana:FPGA_B_GAIN */
#  define FPGA_WRITE_B_OFFSET_GAIN_CTRL                HC_FPGA_WRITE_B_OFFSET_GAIN_CTRL
#  define FPGA_B_GAIN                                  HC_FPGA_WRITE_B_OFFSET_GAIN_CTRL
#define HC_FPGA_READ_FRQ_CHANGE_CTRL                   0x011D   /* belle:FPGA_READ_FRQ_CHANGE_CTRL */
#  define FPGA_READ_FRQ_CHANGE_CTRL                    HC_FPGA_READ_FRQ_CHANGE_CTRL
#define HC_FPGA_WRITE_FRQ_CHANGE_CTRL                  0x011E   /* belle:FPGA_WRITE_FRQ_CHANGE_CTRL */
#  define FPGA_WRITE_FRQ_CHANGE_CTRL                   HC_FPGA_WRITE_FRQ_CHANGE_CTRL
#define HC_FPGA_READ_IMAGE_PROCESS_CTRL                0x011F   /* belle:FPGA_READ_IMAGE_PROCESS_CTRL */
#  define FPGA_READ_IMAGE_PROCESS_CTRL                 HC_FPGA_READ_IMAGE_PROCESS_CTRL
#define HC_FPGA_WRITE_IMAGE_PROCESS_CTRL               0x0120   /* belle:FPGA_WRITE_IMAGE_PROCESS_CTRL */
#  define FPGA_WRITE_IMAGE_PROCESS_CTRL                HC_FPGA_WRITE_IMAGE_PROCESS_CTRL
#define HC_FPGA_READ_MANUAL_MODE                       0x0121   /* belle:FPGA_READ_MANUAL_MODE */
#  define FPGA_READ_MANUAL_MODE                        HC_FPGA_READ_MANUAL_MODE
#define HC_FPGA_WRITE_MANUAL_MODE                      0x0122   /* belle:FPGA_WRITE_MANUAL_MODE */
#  define FPGA_WRITE_MANUAL_MODE                       HC_FPGA_WRITE_MANUAL_MODE
#define HC_FPGA_READ_FREQUENCY                         0x0123   /* belle:FPGA_READ_FREQUENCY */
#  define FPGA_READ_FREQUENCY                          HC_FPGA_READ_FREQUENCY
#define HC_FPGA_WRITE_FREQUENCY                        0x0124   /* belle:FPGA_WRITE_FREQUENCY moana:FPGA_TX_FREQUENCY */
#  define FPGA_WRITE_FREQUENCY                         HC_FPGA_WRITE_FREQUENCY
#  define FPGA_TX_FREQUENCY                            HC_FPGA_WRITE_FREQUENCY
#define HC_FPGA_READ_MULTI_FOCAL_LENGTH                0x0125   /* belle:FPGA_READ_MULTI_FOCAL_LENGTH */
#  define FPGA_READ_MULTI_FOCAL_LENGTH                 HC_FPGA_READ_MULTI_FOCAL_LENGTH
#define HC_FPGA_WRITE_MULTI_FOCAL_LENGTH               0x0126   /* belle:FPGA_WRITE_MULTI_FOCAL_LENGTH moana:FPGA_MULTI_FOCAL */
#  define FPGA_WRITE_MULTI_FOCAL_LENGTH                HC_FPGA_WRITE_MULTI_FOCAL_LENGTH
#  define FPGA_MULTI_FOCAL                             HC_FPGA_WRITE_MULTI_FOCAL_LENGTH
#define HC_FPGA_READ_MULTI_BLENDING                    0x0127   /* belle:FPGA_READ_MULTI_BLENDING */
#  define FPGA_READ_MULTI_BLENDING                     HC_FPGA_READ_MULTI_BLENDING
#define HC_FPGA_WRITE_MULTI_BLENDING                   0x0128   /* belle:FPGA_WRITE_MULTI_BLENDING */
#  define FPGA_WRITE_MULTI_BLENDING                    HC_FPGA_WRITE_MULTI_BLENDING
#define HC_FPGA_COLOR_DOPPLER_CTRL                     0x0200   /* belle:FPGA_COLOR_DOPPLER_CTRL moana:FPGA_DOPPLER_CTRL */
#  define FPGA_COLOR_DOPPLER_CTRL                      HC_FPGA_COLOR_DOPPLER_CTRL
#  define FPGA_DOPPLER_CTRL                            HC_FPGA_COLOR_DOPPLER_CTRL
#define HC_FPGA_READ_COLOR_DOPPLER_PARAM               0x0201   /* belle:FPGA_READ_COLOR_DOPPLER_PARAM moana:FPGA_READ_DOPPLER_PARAM */
#  define FPGA_READ_COLOR_DOPPLER_PARAM                HC_FPGA_READ_COLOR_DOPPLER_PARAM
#  define FPGA_READ_DOPPLER_PARAM                      HC_FPGA_READ_COLOR_DOPPLER_PARAM
#define HC_FPGA_WRITE_COLOR_DOPPLER_PARAM              0x0202   /* belle:FPGA_WRITE_COLOR_DOPPLER_PARAM moana:FPGA_WRITE_DOPPLER_PARAM */
#  define FPGA_WRITE_COLOR_DOPPLER_PARAM               HC_FPGA_WRITE_COLOR_DOPPLER_PARAM
#  define FPGA_WRITE_DOPPLER_PARAM                     HC_FPGA_WRITE_COLOR_DOPPLER_PARAM
#define HC_FPGA_READ_ADC_DUMP_MODE_CTRL                0x0203   /* belle:FPGA_READ_ADC_DUMP_MODE_CTRL */
#  define FPGA_READ_ADC_DUMP_MODE_CTRL                 HC_FPGA_READ_ADC_DUMP_MODE_CTRL
#define HC_FPGA_WRITE_ADC_DUMP_MODE_CTRL               0x0204   /* belle:FPGA_WRITE_ADC_DUMP_MODE_CTRL */
#  define FPGA_WRITE_ADC_DUMP_MODE_CTRL                HC_FPGA_WRITE_ADC_DUMP_MODE_CTRL
#define HC_FPGA_READ_TX_STEER                          0x0205   /* belle:FPGA_READ_TX_STEER */
#  define FPGA_READ_TX_STEER                           HC_FPGA_READ_TX_STEER
#define HC_FPGA_WRITE_TX_STEER                         0x0206   /* belle:FPGA_WRITE_TX_STEER */
#  define FPGA_WRITE_TX_STEER                          HC_FPGA_WRITE_TX_STEER
#define HC_FPGA_READ_LINE_DENSITY                      0x0207   /* belle:FPGA_READ_LINE_DENSITY */
#  define FPGA_READ_LINE_DENSITY                       HC_FPGA_READ_LINE_DENSITY
#define HC_FPGA_WRITE_LINE_DENSITY                     0x0208   /* belle:FPGA_WRITE_LINE_DENSITY moana:FPGA_LINE_DENSITY */
#  define FPGA_WRITE_LINE_DENSITY                      HC_FPGA_WRITE_LINE_DENSITY
#  define FPGA_LINE_DENSITY                            HC_FPGA_WRITE_LINE_DENSITY
#define HC_FPGA_READ_SCAN_SAMPLES                      0x0209   /* belle:FPGA_READ_SCAN_SAMPLES */
#  define FPGA_READ_SCAN_SAMPLES                       HC_FPGA_READ_SCAN_SAMPLES
#define HC_FPGA_WRITE_SCAN_SAMPLES                     0x020A   /* belle:FPGA_WRITE_SCAN_SAMPLES moana:FPGA_SAMPLE_512 */
#  define FPGA_WRITE_SCAN_SAMPLES                      HC_FPGA_WRITE_SCAN_SAMPLES
#  define FPGA_SAMPLE_512                              HC_FPGA_WRITE_SCAN_SAMPLES
#define HC_FPGA_READ_C_MODE_GAIN                       0x020B   /* belle:FPGA_READ_C_MODE_GAIN */
#  define FPGA_READ_C_MODE_GAIN                        HC_FPGA_READ_C_MODE_GAIN
#define HC_FPGA_WRITE_C_MODE_GAIN                      0x020C   /* belle:FPGA_WRITE_C_MODE_GAIN moana:FPGA_C_GAIN */
#  define FPGA_WRITE_C_MODE_GAIN                       HC_FPGA_WRITE_C_MODE_GAIN
#  define FPGA_C_GAIN                                  HC_FPGA_WRITE_C_MODE_GAIN
#define HC_FPGA_READ_COLOR_DOPPLER_FILTER_SET          0x0220   /* belle:FPGA_READ_COLOR_DOPPLER_FILTER_SET moana:FPGA_READ_CF_FILTER_SETTING */
#  define FPGA_READ_COLOR_DOPPLER_FILTER_SET           HC_FPGA_READ_COLOR_DOPPLER_FILTER_SET
#  define FPGA_READ_CF_FILTER_SETTING                  HC_FPGA_READ_COLOR_DOPPLER_FILTER_SET
#define HC_FPGA_WRITE_COLOR_DOPPLER_FILTER_SET         0x0221   /* belle:FPGA_WRITE_COLOR_DOPPLER_FILTER_SET moana:FPGA_WRITE_CF_FILTER_SETTING */
#  define FPGA_WRITE_COLOR_DOPPLER_FILTER_SET          HC_FPGA_WRITE_COLOR_DOPPLER_FILTER_SET
#  define FPGA_WRITE_CF_FILTER_SETTING                 HC_FPGA_WRITE_COLOR_DOPPLER_FILTER_SET
#define HC_FPGA_DBG_DOPPLER_COEF                       0x0301   /* belle:FPGA_DBG_DOPPLER_COEF */
#  define FPGA_DBG_DOPPLER_COEF                        HC_FPGA_DBG_DOPPLER_COEF
#define HC_FPGA_WRITE_SA                               0x0306   /* belle:FPGA_WRITE_SA moana:FPGA_SA_MODE */
#  define FPGA_WRITE_SA                                HC_FPGA_WRITE_SA
#  define FPGA_SA_MODE                                 HC_FPGA_WRITE_SA
#define HC_FPGA_READ_SA                                0x0307   /* belle:FPGA_READ_SA */
#  define FPGA_READ_SA                                 HC_FPGA_READ_SA
#define HC_FPGA_WRITE_DP_FOCAL_LENGTH                  0x0308   /* belle:FPGA_WRITE_DP_FOCAL_LENGTH moana:FPGA_WRITE_DP_FOCAL */
#  define FPGA_WRITE_DP_FOCAL_LENGTH                   HC_FPGA_WRITE_DP_FOCAL_LENGTH
#  define FPGA_WRITE_DP_FOCAL                          HC_FPGA_WRITE_DP_FOCAL_LENGTH
#define HC_FPGA_READ_DP_FOCAL_LENGTH                   0x0309   /* belle:FPGA_READ_DP_FOCAL_LENGTH moana:FPGA_READ_DP_FOCAL */
#  define FPGA_READ_DP_FOCAL_LENGTH                    HC_FPGA_READ_DP_FOCAL_LENGTH
#  define FPGA_READ_DP_FOCAL                           HC_FPGA_READ_DP_FOCAL_LENGTH
#define HC_FPGA_SET_DEBUG_DUMP                         0x0400   /* moana:FPGA_SET_DEBUG_DUMP */
#  define FPGA_SET_DEBUG_DUMP                          HC_FPGA_SET_DEBUG_DUMP
#define HC_FPGA_READY_DEBUG_DUMP                       0x0401   /* moana:FPGA_READY_DEBUG_DUMP */
#  define FPGA_READY_DEBUG_DUMP                        HC_FPGA_READY_DEBUG_DUMP
#define HC_FPGA_GET_DEBUG_DUMP                         0x0402   /* moana:FPGA_GET_DEBUG_DUMP */
#  define FPGA_GET_DEBUG_DUMP                          HC_FPGA_GET_DEBUG_DUMP
#define HC_FPGA_DBG_CAPTURE_FRAME                      0x1003   /* belle:FPGA_DBG_CAPTURE_FRAME */
#  define FPGA_DBG_CAPTURE_FRAME                       HC_FPGA_DBG_CAPTURE_FRAME
#define HC_FPGA_DBG_ADC_DUMP_DATA                      0x1004   /* belle:FPGA_DBG_ADC_DUMP_DATA */
#  define FPGA_DBG_ADC_DUMP_DATA                       HC_FPGA_DBG_ADC_DUMP_DATA
#define HC_FPGA_WRITE_B_FUNC                           0x1005   /* moana:FPGA_WRITE_B_FUNC */
#  define FPGA_WRITE_B_FUNC                            HC_FPGA_WRITE_B_FUNC
#define HC_FPGA_PW_READ_PARAM                          0x4000   /* belle:FPGA_PW_READ_PARAM moana:FPGA_READ_PW_PARAM */
#  define FPGA_PW_READ_PARAM                           HC_FPGA_PW_READ_PARAM
#  define FPGA_READ_PW_PARAM                           HC_FPGA_PW_READ_PARAM
#define HC_FPGA_PW_WRITE_PARAM                         0x4001   /* belle:FPGA_PW_WRITE_PARAM moana:FPGA_WRITE_PW_PARAM */
#  define FPGA_PW_WRITE_PARAM                          HC_FPGA_PW_WRITE_PARAM
#  define FPGA_WRITE_PW_PARAM                          HC_FPGA_PW_WRITE_PARAM
#define HC_FPGA_M_READ_PARAM                           0x5000   /* belle:FPGA_M_READ_PARAM moana:FPGA_READ_M_PARAM */
#  define FPGA_M_READ_PARAM                            HC_FPGA_M_READ_PARAM
#  define FPGA_READ_M_PARAM                            HC_FPGA_M_READ_PARAM
#define HC_FPGA_M_WRITE_PARAM                          0x5001   /* belle:FPGA_M_WRITE_PARAM moana:FPGA_WRITE_M_PARAM */
#  define FPGA_M_WRITE_PARAM                           HC_FPGA_M_WRITE_PARAM
#  define FPGA_WRITE_M_PARAM                           HC_FPGA_M_WRITE_PARAM
#define HC_FPGA_PD_WRITE_PARAM                         0x6001   /* belle:FPGA_PD_WRITE_PARAM moana:FPGA_PD_WRITE_PARAM */
#  define FPGA_PD_WRITE_PARAM                          HC_FPGA_PD_WRITE_PARAM
#define HC_FPGA_PD_READ_PARAM                          0x6002   /* belle:FPGA_PD_READ_PARAM */
#  define FPGA_PD_READ_PARAM                           HC_FPGA_PD_READ_PARAM

/* ---- target id ----------------------------------------------------------------- */
#define HC_TARGET_ID_SERVER                            0x0001   /* belle:HER_TARGET_ID_SERVER moana:HC_HEADER_TARGET_ID_SERVER */
#  define HER_TARGET_ID_SERVER                         HC_TARGET_ID_SERVER
#  define HC_HEADER_TARGET_ID_SERVER                   HC_TARGET_ID_SERVER
#define HC_TARGET_ID_CLIENT                            0x0002   /* belle:HER_TARGET_ID_CLIENT moana:HC_HEADER_TARGET_ID_CLIENT */
#  define HER_TARGET_ID_CLIENT                         HC_TARGET_ID_CLIENT
#  define HC_HEADER_TARGET_ID_CLIENT                   HC_TARGET_ID_CLIENT

/* ---- 500C divergence (recorded, not merged) ------------------------------------ */
/* 0x00F7  device     500C=FW_UPGRADE_START                   belle=(absent) */
/* 0x00F8  device     500C=FW_UPGRADE_WRITE                   belle=(absent) */
/* 0x00F9  device     500C=FW_UPGRADE_VERIFY                  belle=(absent) */
/* 0x00FA  device     500C=FW_UPGRADE_COMPLE                  belle=(absent) */
/* 0x00FB  device     500C=FW_UPGRADE_DONE                    belle=(absent) */
/* 0x0400  fpga       500C=SET_DEBUG_DUMP                     belle=(absent) */
/* 0x0401  fpga       500C=READY_DEBUG_DUMP                   belle=(absent) */
/* 0x0402  fpga       500C=GET_DEBUG_DUMP                     belle=(absent) */
/* 0x1005  fpga       500C=WRITE_B_FUNC                       belle=(absent) */

#ifdef __cplusplus
}   /* extern "C" */
#endif

#endif /* HC_PROTOCOL_H */
